apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: azure-file-myproject
mountOptions: 
- uid=PUT_IT_HERE
- gid=0
- mfsymlinks
- cache=strict
parameters: 
  skuName: Standard_LRS
provisioner: kubernetes.io/azure-file
reclaimPolicy: Delete
volumeBindingMode: Immediate